
export const PRODUCTREQUESTSTATUS  = "PRODUCTREQUESTSTATUS";


export const PRODUCTFAILEDSTATUS  = "PRODUCTFAILEDSTATUS";


export const GETPRODUCTSUCCESSSSTATUS  = "GETPRODUCTSUCCESSSSTATUS";

export const POSTPRODUCTSUCCESS = "POSTPRODUCTSUCCESS"

export const DELETEPRODUCTSUCCESS = "DELETEPRODUCTSUCCESS"

export const PATCHPRODUCTSUCCESS = "PATCHPRODUCTSUCCESS"